<?php

namespace ContainerXqwxkD8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_UtilisateursEnMemoireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.user.provider.concrete.utilisateurs_en_memoire' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\InMemoryUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'InMemoryUserProvider.php';

        return $container->privates['security.user.provider.concrete.utilisateurs_en_memoire'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(['broots' => ['password' => 'toto', 'roles' => [0 => 'ROLE_USER']], 'parker' => ['password' => 'admin', 'roles' => [0 => 'ROLE_ADMIN', 1 => 'ROLE_KILLER']], 'jarod' => ['password' => 'qwerty', 'roles' => [0 => 'ROLE_SUPER_ADMIN']]]);
    }
}
