<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlDfqCi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlDfqCi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPlDfqCi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPlDfqCi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPlDfqCi\App_KernelProdContainer([
    'container.build_hash' => 'PlDfqCi',
    'container.build_id' => '20d87bc5',
    'container.build_time' => 1675674633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlDfqCi');
