<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::indexAction'], [], [['text', '/']], [], [], []],
    'sandbox_overview' => [[], ['_controller' => 'App\\Controller\\Sandbox\\OverviewController::indexAction'], [], [['text', '/sandbox/overview']], [], [], []],
    'sandbox_overview_hello2' => [[], ['_controller' => 'App\\Controller\\Sandbox\\OverviewController::hello2Action'], [], [['text', '/sandbox/overview/hello2']], [], [], []],
    'sandbox_overview_hello3' => [[], ['_controller' => 'App\\Controller\\Sandbox\\OverviewController::hello3Action'], [], [['text', '/sandbox/overview/hello3']], [], [], []],
    'sandbox_overview_hello4' => [[], ['_controller' => 'App\\Controller\\Sandbox\\OverviewController::hello4Action'], [], [['text', '/sandbox/overview/hello4']], [], [], []],
];
