<?php

namespace ContainerPlDfqCi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOverviewControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Sandbox\OverviewController' shared autowired service.
     *
     * @return \App\Controller\Sandbox\OverviewController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Sandbox\\OverviewController'] = $instance = new \App\Controller\Sandbox\OverviewController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\Sandbox\\OverviewController', $container));

        return $instance;
    }
}
