<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1uah2SU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1uah2SU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1uah2SU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1uah2SU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1uah2SU\App_KernelDevDebugContainer([
    'container.build_hash' => '1uah2SU',
    'container.build_id' => '08ba70a1',
    'container.build_time' => 1679475884,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1uah2SU');
