<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLQ5hVZH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLQ5hVZH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLQ5hVZH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLQ5hVZH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLQ5hVZH\App_KernelDevDebugContainer([
    'container.build_hash' => 'LQ5hVZH',
    'container.build_id' => '1c13d587',
    'container.build_time' => 1679388480,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLQ5hVZH');
