<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTrASbnv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTrASbnv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTrASbnv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTrASbnv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTrASbnv\App_KernelDevDebugContainer([
    'container.build_hash' => 'TrASbnv',
    'container.build_id' => '03a8230a',
    'container.build_time' => 1678952714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTrASbnv');
